apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shell-operator

resources:
- shell-operator.yaml

images:
- name: shell-operator
  newName: cgik/testing
  newTag: shell-operator