apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- shell-operator-rbac.yaml
- shell-operator.yaml

images:
- name: shell-operator
  newName: cgik/testing
  newTag: shell-operator