apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shell-operator
resources:
- shell-operator-ns.yaml
- shell-operator-pod.yaml
- shell-operator-rbac.yaml
images:
- name: shell-operator
  newName: cgik/testing:shell-operator
  #newTag: latest