---
apiVersion: v1
kind: Namespace
metadata:
  name: shell-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-namespaces-acc
  namespace: shell-operator


---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: shell-operator
    imagePullPolicy: Always
  serviceAccountName: monitor-namespaces-acc

