apiVersion: v1
kind: Namespace
metadata:
  name: shell-operator
---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: 
    imagePullPolicy: Always