---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: shell-operator
    imagePullPolicy: Always
  serviceAccountName: monitor-namespaces-acc