---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator-pod
  namespace: shell-operator
spec:
  containers:
  - name: shell-operator-container
    image: shell-operator
    imagePullPolicy: Always
  serviceAccountName: default
  automountServiceAccountToken: false
